# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'

# 使用的主題
theme = "papermod"

# 網站網址，先維持預設
baseURL = "https://example.org/"

# 預設網站語言
languageCode = "en-us"

# 網站標題
title = "My New Hugo Site"
